import type { DiagnosisV2Config } from '@/types/diagnosisV2';

export const careerChangeV2: DiagnosisV2Config = {
  id: 'career-change',
  title: '転職市場価値診断',
  subtitle: '12の質問で、あなたの今の市場価値と動くべきタイミングが見えてきます',
  traits: [
    {
      key: 'urgency',
      label: '緊急度',
      lowLabel: '様子を見ながら考えたい',
      highLabel: '今すぐ動きたい',
      color: '#38A1D6',
    },
    {
      key: 'selfAwareness',
      label: '市場価値自覚度',
      lowLabel: '客観視できていない',
      highLabel: '自分の価値を把握している',
      color: '#D4AF37',
    },
    {
      key: 'negotiation',
      label: '条件交渉志向',
      lowLabel: '提示条件で十分',
      highLabel: '積極的に交渉したい',
      color: '#8FB8E0',
    },
    {
      key: 'comparison',
      label: '比較検討志向',
      lowLabel: '一つに絞って深く考えたい',
      highLabel: '多くの選択肢を比較したい',
      color: '#C0D6F2',
    },
  ],
  questions: [
    {
      id: 'q1',
      type: 'choice',
      prompt: '今の自分の市場価値について、正直にどう感じていますか？',
      options: [
        { label: '全く把握できていない', sublabel: '', effects: { selfAwareness: -1.3 } },
        { label: 'なんとなくのイメージはある', sublabel: '', effects: { selfAwareness: -0.4 } },
        { label: 'ある程度具体的に把握している', sublabel: '', effects: { selfAwareness: 0.7 } },
        { label: '数字やデータで把握している', sublabel: '', effects: { selfAwareness: 1.4, negotiation: 0.5 } },
      ],
    },
    {
      id: 'q2',
      type: 'slider',
      prompt: '転職を考えるなら、今すぐ動きたい気持ちはどのくらいありますか？',
      lowAnchor: 'まだ様子を見たい',
      highAnchor: '今すぐ動きたい',
      trait: 'urgency',
      direction: 1,
    },
    {
      id: 'q3',
      type: 'choice',
      prompt: '転職を考え始めたきっかけに、一番近いものは？',
      options: [
        { label: '今の給与に納得していない', sublabel: '', effects: { negotiation: 1, urgency: 0.5 } },
        { label: '将来への漠然とした不安', sublabel: '', effects: { urgency: -0.4, selfAwareness: -0.4 } },
        { label: '今より良い環境を試したい', sublabel: '', effects: { comparison: 0.8 } },
        { label: '特に強いきっかけはまだない', sublabel: '', effects: { urgency: -0.9 } },
      ],
    },
    {
      id: 'q4',
      type: 'slider',
      prompt: '年収や条件の交渉について、積極的にやりたいですか？',
      lowAnchor: '提示された条件で十分',
      highAnchor: '積極的に交渉したい',
      trait: 'negotiation',
      direction: 1,
    },
    {
      id: 'q5',
      type: 'choice',
      prompt: '転職活動の進め方として、しっくりくるのは？',
      options: [
        { label: '一社ずつじっくり検討したい', sublabel: '', effects: { comparison: -1 } },
        { label: '複数社を並行して比較したい', sublabel: '', effects: { comparison: 1.2 } },
        { label: 'まずは情報収集だけしたい', sublabel: '', effects: { urgency: -0.6, comparison: 0.4 } },
        { label: '良い話があればすぐ動きたい', sublabel: '', effects: { urgency: 1, comparison: -0.4 } },
      ],
    },
    {
      id: 'q6',
      type: 'slider',
      prompt: '今の年収は、自分の実力に見合っていると感じますか？',
      lowAnchor: '見合っていないと感じる',
      highAnchor: '見合っていると感じる',
      trait: 'negotiation',
      direction: -1,
    },
    {
      id: 'q7',
      type: 'choice',
      prompt: '自分の経歴やスキルを、客観的なデータと照らし合わせたことはありますか？',
      options: [
        { label: 'まったくない', sublabel: '', effects: { selfAwareness: -1 } },
        { label: 'なんとなく調べたことがある', sublabel: '', effects: { selfAwareness: -0.3 } },
        { label: '一度しっかり診断したことがある', sublabel: '', effects: { selfAwareness: 0.8 } },
        { label: '定期的に市場価値をチェックしている', sublabel: '', effects: { selfAwareness: 1.3, urgency: 0.4 } },
      ],
    },
    {
      id: 'q8',
      type: 'slider',
      prompt: '転職先候補は、できるだけ多く比較したいですか？',
      lowAnchor: '一つに絞って深く考えたい',
      highAnchor: 'たくさん比較したい',
      trait: 'comparison',
      direction: 1,
    },
    {
      id: 'q9',
      type: 'choice',
      prompt: '今、転職に踏み切れない一番の理由は？',
      options: [
        { label: '自分の市場価値に自信が持てない', sublabel: '', effects: { selfAwareness: -1, urgency: -0.5 } },
        { label: '今より悪い条件になるのが怖い', sublabel: '', effects: { negotiation: -0.6 } },
        { label: '何から始めればいいか分からない', sublabel: '', effects: { urgency: -0.4, comparison: 0.4 } },
        { label: '特に踏み切れない理由はない', sublabel: '', effects: { urgency: 1.2 } },
      ],
    },
    {
      id: 'q10',
      type: 'slider',
      prompt: '今の市場での「旬」を逃したくないという焦りはありますか？',
      lowAnchor: 'あまり焦りはない',
      highAnchor: 'かなり焦りがある',
      trait: 'urgency',
      direction: 1,
    },
    {
      id: 'q11',
      type: 'choice',
      prompt: '転職活動で一番欲しいサポートは？',
      options: [
        { label: '客観的な市場価値の診断', sublabel: '', effects: { selfAwareness: 0.8 } },
        { label: '条件交渉の代行・アドバイス', sublabel: '', effects: { negotiation: 1.1 } },
        { label: '多くの求人を一気に見比べる手段', sublabel: '', effects: { comparison: 1 } },
        { label: '今動くべきかどうかの判断材料', sublabel: '', effects: { urgency: 0.6, selfAwareness: 0.4 } },
      ],
    },
    {
      id: 'q12',
      type: 'slider',
      prompt: '最後に。「今の自分の市場価値を正確に知りたい」という気持ちは、どのくらいありますか？',
      lowAnchor: 'あまりない',
      highAnchor: 'かなりある',
      trait: 'selfAwareness',
      direction: 1,
    },
  ],
  services: [
    {
      id: 'spi-agent',
      name: 'SPI転職エージェント',
      tagline: '転職のプロによるパーソナルサポート。完全無料で転職活動を支援したい人へ',
      emoji: '🤝',
      bannerImage: 'https://image.moshimo.com/af-img/6249/000000094548.jpg',
      bannerWidth: 200,
      bannerHeight: 200,
      impUrl: 'https://i.moshimo.com/af/i/impression?a_id=5646088&p_id=7540&pc_id=21772&pl_id=94548',
      href: 'https://af.moshimo.com/af/c/click?a_id=5646088&p_id=7540&pc_id=21772&pl_id=94548',
      isAffiliate: true,
      comingSoon: false,
    },
    {
      id: 'neko-agent',
      name: 'ネコエージェント（LINE転職相談）',
      tagline: 'LINEで気軽に相談しながら、自分のペースで転職活動を進めたい人へ',
      emoji: '🐱',
      bannerImage: 'https://image.moshimo.com/af-img/7386/000000094960.jpg',
      bannerWidth: 260,
      bannerHeight: 462,
      impUrl: 'https://i.moshimo.com/af/i/impression?a_id=5646086&p_id=7593&pc_id=21950&pl_id=94960',
      href: 'https://af.moshimo.com/af/c/click?a_id=5646086&p_id=7593&pc_id=21950&pl_id=94960',
      isAffiliate: true,
      comingSoon: false,
    },
    {
      id: 'massmediann',
      name: 'マスメディアン（転職）',
      tagline: 'マーケ・広告・IT業界への転職に特化したエージェントを使いたい人へ',
      emoji: '📣',
      bannerImage: 'https://www22.a8.net/svt/bgt?aid=260607748678&wid=004&eno=01&mid=s00000016542001059000&mc=1',
      bannerWidth: 200,
      bannerHeight: 50,
      impUrl: 'https://www17.a8.net/0.gif?a8mat=4B5Q84+B7NZ8Q+3JN0+6AZAP',
      href: 'https://px.a8.net/svt/ejp?a8mat=4B5Q84+B7NZ8Q+3JN0+6AZAP',
      isAffiliate: true,
      comingSoon: false,
    },
    {
      id: 'cype',
      name: 'Cype（女性の転職エージェント）',
      tagline: '女性専門の転職エージェント。育児・ブランクOKの求人を多数保有',
      emoji: '👩‍💼',
      bannerImage: 'https://image.moshimo.com/af-img/6249/000000094550.jpg',
      bannerWidth: 200,
      bannerHeight: 200,
      impUrl: 'https://i.moshimo.com/af/i/impression?a_id=5646089&p_id=7541&pc_id=21774&pl_id=94550',
      href: 'https://af.moshimo.com/af/c/click?a_id=5646089&p_id=7541&pc_id=21774&pl_id=94550',
      isAffiliate: true,
      comingSoon: false,
    },
    {
      id: 'remoful',
      name: 'Remoful（リモートワーク転職）',
      tagline: 'フルリモートで働きたい・在宅ワークに特化した求人を探したい人へ',
      emoji: '💻',
      bannerImage: 'https://image.moshimo.com/af-img/1052/000000075329.png',
      bannerWidth: 200,
      bannerHeight: 200,
      impUrl: 'https://i.moshimo.com/af/i/impression?a_id=5646096&p_id=5870&pc_id=16301&pl_id=75329',
      href: 'https://af.moshimo.com/af/c/click?a_id=5646096&p_id=5870&pc_id=16301&pl_id=75329',
      isAffiliate: true,
      comingSoon: false,
    },
  ],
};
