import type { DiagnosisV2Config } from '@/types/diagnosisV2';

export const careerStartV2: DiagnosisV2Config = {
  id: 'career',
  title: '就活キャリア診断',
  subtitle: '12の質問で、あなたに合う就活の進め方が見えてきます',
  traits: [
    {
      key: 'stability',
      label: '安定志向',
      lowLabel: '挑戦的な環境がいい',
      highLabel: '安定した環境がいい',
      color: '#38A1D6',
    },
    {
      key: 'expression',
      label: '自己表現力',
      lowLabel: '言語化に自信がない',
      highLabel: '自己PRに自信がある',
      color: '#D4AF37',
    },
    {
      key: 'clarity',
      label: '業界明確度',
      lowLabel: 'まだ模索中',
      highLabel: '志望業界が明確',
      color: '#8FB8E0',
    },
    {
      key: 'guidance',
      label: 'サポート希求度',
      lowLabel: '自分のペースで進めたい',
      highLabel: '手厚い対策がほしい',
      color: '#C0D6F2',
    },
  ],
  questions: [
    {
      id: 'q1',
      type: 'choice',
      prompt: '今の就活の状況に、一番近いものは？',
      options: [
        { label: 'まだ何も始めていない', sublabel: '', effects: { clarity: -0.8, guidance: 0.6 } },
        { label: '情報収集を始めたところ', sublabel: '', effects: { clarity: -0.3 } },
        { label: 'エントリーを始めている', sublabel: '', effects: { clarity: 0.5 } },
        { label: '面接段階まで進んでいる', sublabel: '', effects: { clarity: 0.9, expression: 0.4 } },
      ],
    },
    {
      id: 'q2',
      type: 'slider',
      prompt: '就活で重視したいのは、安定性と挑戦のどちらに近いですか？',
      lowAnchor: '挑戦できる環境がいい',
      highAnchor: '安定した環境がいい',
      trait: 'stability',
      direction: 1,
    },
    {
      id: 'q3',
      type: 'choice',
      prompt: '自己PRや面接への自信は、正直どのくらいありますか？',
      options: [
        { label: 'かなり不安が大きい', sublabel: '', effects: { expression: -1.3, guidance: 1 } },
        { label: '少し自信がない', sublabel: '', effects: { expression: -0.6, guidance: 0.5 } },
        { label: 'まあまあ自信がある', sublabel: '', effects: { expression: 0.6 } },
        { label: '自信がある', sublabel: '', effects: { expression: 1.3, guidance: -0.5 } },
      ],
    },
    {
      id: 'q4',
      type: 'slider',
      prompt: '志望する業界や職種は、どのくらい絞れていますか？',
      lowAnchor: 'まだ絞れていない',
      highAnchor: 'かなり絞れている',
      trait: 'clarity',
      direction: 1,
    },
    {
      id: 'q5',
      type: 'choice',
      prompt: '就活エージェントや支援サービスに期待するのは？',
      options: [
        { label: '一緒に考えてくれる伴走サポート', sublabel: '', effects: { guidance: 1.3 } },
        { label: '客観的な企業データや情報', sublabel: '', effects: { guidance: -0.3, clarity: 0.4 } },
        { label: '面接や書類の具体的な添削', sublabel: '', effects: { expression: -0.5, guidance: 0.8 } },
        { label: '特にサポートは不要、自分でやれる', sublabel: '', effects: { guidance: -1.2, expression: 0.5 } },
      ],
    },
    {
      id: 'q6',
      type: 'slider',
      prompt: '大手企業とベンチャー企業、本音はどちらに惹かれますか？',
      lowAnchor: 'ベンチャーで裁量を持ちたい',
      highAnchor: '大手で安定して働きたい',
      trait: 'stability',
      direction: 1,
    },
    {
      id: 'q7',
      type: 'choice',
      prompt: '自分の強みを聞かれたとき、どう感じますか？',
      options: [
        { label: 'うまく言葉にできない', sublabel: '', effects: { expression: -1.2, guidance: 0.8 } },
        { label: '考えればなんとか言える', sublabel: '', effects: { expression: -0.3 } },
        { label: 'いくつか具体的に言える', sublabel: '', effects: { expression: 0.7 } },
        { label: 'エピソードを交えて明確に言える', sublabel: '', effects: { expression: 1.4 } },
      ],
    },
    {
      id: 'q8',
      type: 'slider',
      prompt: '業界研究や企業研究は、どのくらい進んでいますか？',
      lowAnchor: 'まだほとんどできていない',
      highAnchor: 'かなり研究できている',
      trait: 'clarity',
      direction: 1,
    },
    {
      id: 'q9',
      type: 'choice',
      prompt: '就活で一番不安に感じていることは？',
      options: [
        { label: '何から始めればいいか分からない', sublabel: '', effects: { guidance: 1.2, clarity: -0.5 } },
        { label: '面接でうまく話せるか', sublabel: '', effects: { expression: -0.8 } },
        { label: '本当にやりたいことが分からない', sublabel: '', effects: { clarity: -1, guidance: 0.6 } },
        { label: '内定が取れるか競争が不安', sublabel: '', effects: { stability: 0.5, guidance: 0.4 } },
      ],
    },
    {
      id: 'q10',
      type: 'slider',
      prompt: '複数の選考対策を一人で進めるより、誰かと一緒に進めたいですか？',
      lowAnchor: '自分のペースで進めたい',
      highAnchor: '誰かと一緒に進めたい',
      trait: 'guidance',
      direction: 1,
    },
    {
      id: 'q11',
      type: 'choice',
      prompt: '働き方として、理想に近いのはどちらですか？',
      options: [
        { label: '腰を据えて長く働ける環境', sublabel: '', effects: { stability: 1.2 } },
        { label: '成長機会が多い環境', sublabel: '', effects: { stability: -0.8 } },
        { label: '専門性を磨ける環境', sublabel: '', effects: { clarity: 0.6 } },
        { label: 'まだ具体的にイメージできていない', sublabel: '', effects: { clarity: -0.6, guidance: 0.5 } },
      ],
    },
    {
      id: 'q12',
      type: 'slider',
      prompt: '最後に。「内定をしっかり勝ち取りたい」という気持ちは、どのくらい強いですか？',
      lowAnchor: 'プレッシャーは感じたくない',
      highAnchor: '強く勝ち取りたい',
      trait: 'expression',
      direction: 1,
    },
  ],
  services: [
    {
      id: 'caricen',
      name: 'キャリセン就活エージェント',
      tagline: '内定ゼロ・出遅れでも諦めないで。就活を立て直す個別サポートの無料相談',
      emoji: '🎓',
      bannerImage: 'https://image.moshimo.com/af-img/7206/000000092960.jpg',
      bannerWidth: 100,
      bannerHeight: 60,
      impUrl: 'https://i.moshimo.com/af/i/impression?a_id=5646099&p_id=7382&pc_id=21253&pl_id=92960',
      href: 'https://af.moshimo.com/af/c/click?a_id=5646099&p_id=7382&pc_id=21253&pl_id=92960',
      isAffiliate: true,
      comingSoon: false,
    },
    {
      id: 'kimisuka',
      name: 'キミスカ（就活エージェント）',
      tagline: 'スカウト型就活で、自分に合う企業から声をかけてもらいたい人へ',
      emoji: '📬',
      bannerImage: 'https://www26.a8.net/svt/bgt?aid=260623887926&wid=004&eno=01&mid=s00000009978003030000&mc=1',
      bannerWidth: 300,
      bannerHeight: 240,
      impUrl: 'https://www15.a8.net/0.gif?a8mat=4B62OF+FBBH9M+24ZO+I1FMP',
      href: 'https://px.a8.net/svt/ejp?a8mat=4B62OF+FBBH9M+24ZO+I1FMP',
      isAffiliate: true,
      comingSoon: false,
    },
    {
      id: 'transfer-agent-navi',
      name: '転職AGENT Navi',
      tagline: '自分に合った転職エージェントを無料で紹介してもらいたい人へ',
      emoji: '🗺️',
      bannerImage: 'https://www24.a8.net/svt/bgt?aid=260623887958&wid=004&eno=01&mid=s00000024824001006000&mc=1',
      bannerWidth: 100,
      bannerHeight: 60,
      impUrl: 'https://www13.a8.net/0.gif?a8mat=4B62OF+FUDCMI+5BJK+5ZMCH',
      href: 'https://px.a8.net/svt/ejp?a_id=5646082&a8mat=4B62OF+FUDCMI+5BJK+5ZMCH',
      isAffiliate: true,
      comingSoon: false,
    },
    {
      id: 'caripato',
      name: 'キャリパト（キャリアコーチング）',
      tagline: '2ヶ月で選択できる自分に。キャリア戦略を一緒に考えてほしい人へ',
      emoji: '🎯',
      bannerImage: 'https://image.moshimo.com/af-img/7222/000000093491.png',
      bannerWidth: 120,
      bannerHeight: 60,
      impUrl: 'https://i.moshimo.com/af/i/impression?a_id=5646097&p_id=7422&pc_id=21397&pl_id=93491',
      href: 'https://af.moshimo.com/af/c/click?a_id=5646097&p_id=7422&pc_id=21397&pl_id=93491',
      isAffiliate: true,
      comingSoon: false,
    },
    {
      id: 'spi-agent',
      name: 'SPI転職エージェント',
      tagline: '転職のプロによるパーソナルサポート。完全無料で転職活動を支援したい人へ',
      emoji: '🤝',
      bannerImage: 'https://image.moshimo.com/af-img/6249/000000094548.jpg',
      bannerWidth: 200,
      bannerHeight: 200,
      impUrl: 'https://i.moshimo.com/af/i/impression?a_id=5646088&p_id=7540&pc_id=21772&pl_id=94548',
      href: 'https://af.moshimo.com/af/c/click?a_id=5646088&p_id=7540&pc_id=21772&pl_id=94548',
      isAffiliate: true,
      comingSoon: false,
    },
  ],
};
