import type { DiagnosisV2Config } from '@/types/diagnosisV2';

export const salaryUpV2: DiagnosisV2Config = {
  id: 'salary-up',
  title: '年収アップ行動診断',
  subtitle: '12の質問で、あなたが本当に求めている働き方が見えてきます',
  traits: [
    {
      key: 'support',
      label: '伴走サポート志向',
      lowLabel: '自立して進めたい',
      highLabel: '手厚くサポートしてほしい',
      color: '#38A1D6',
    },
    {
      key: 'income',
      label: '収入優先度',
      lowLabel: '環境ややりがいも大事',
      highLabel: 'とにかく収入を上げたい',
      color: '#D4AF37',
    },
    {
      key: 'speed',
      label: 'スピード重視',
      lowLabel: 'じっくり準備したい',
      highLabel: '今すぐ動きたい',
      color: '#8FB8E0',
    },
    {
      key: 'expertise',
      label: '専門性志向',
      lowLabel: '幅広く可能性を探りたい',
      highLabel: '専門スキルを極めたい',
      color: '#C0D6F2',
    },
  ],
  questions: [
    {
      id: 'q1',
      type: 'choice',
      prompt: '今の働き方に、正直どのくらい満足していますか？',
      options: [
        { label: 'かなり不満がある', sublabel: '何かを変えたい気持ちが強い', effects: { speed: 1, support: 0.5 } },
        { label: 'やや不満がある', sublabel: 'モヤモヤを抱えている', effects: { speed: 0.5 } },
        { label: 'まあまあ満足している', sublabel: 'でも伸びしろは感じる', effects: { speed: -0.5 } },
        { label: '満足している', sublabel: 'さらに上を目指したい', effects: { income: 0.8, speed: -0.8 } },
      ],
    },
    {
      id: 'q2',
      type: 'slider',
      prompt: '転職や副業を考えたとき、今すぐ動きたい気持ちはどのくらいありますか？',
      lowAnchor: 'まず情報収集したい',
      highAnchor: '今すぐ動きたい',
      trait: 'speed',
      direction: 1,
    },
    {
      id: 'q3',
      type: 'choice',
      prompt: '自分の市場価値について、正直にどう感じていますか？',
      options: [
        { label: 'かなり自信がない', sublabel: '何から手をつければいいか分からない', effects: { support: 1.5, speed: -0.5 } },
        { label: '少し不安がある', sublabel: '人と比べると弱気になる', effects: { support: 0.8 } },
        { label: 'まあまあ自信がある', sublabel: '強みは分かっている', effects: { support: -0.5, income: 0.5 } },
        { label: 'かなり自信がある', sublabel: 'もっと評価されてもいいと思う', effects: { support: -1.2, income: 1.2 } },
      ],
    },
    {
      id: 'q4',
      type: 'slider',
      prompt: '「年収」と「働きがい・人間関係」、本音はどちらに比重がありますか？',
      lowAnchor: '働きがい重視',
      highAnchor: '年収重視',
      trait: 'income',
      direction: 1,
    },
    {
      id: 'q5',
      type: 'choice',
      prompt: '希望する働き方の環境は、どちらに近いですか？',
      options: [
        { label: '大手で安定して評価されたい', sublabel: '', effects: { income: 0.6, speed: -0.5, support: 0.4 } },
        { label: 'ベンチャーで裁量を持ちたい', sublabel: '', effects: { speed: 0.8, support: -0.6 } },
        { label: '同じ業界・職種で深めたい', sublabel: '', effects: { expertise: 1.2 } },
        { label: '未経験の分野に挑戦したい', sublabel: '', effects: { expertise: -1, speed: 0.5 } },
      ],
    },
    {
      id: 'q6',
      type: 'slider',
      prompt: '転職・副業のサポートで、どこまで頼りたいですか？',
      lowAnchor: '自分で情報を集めて判断したい',
      highAnchor: '相談しながら一緒に進めたい',
      trait: 'support',
      direction: 1,
    },
    {
      id: 'q7',
      type: 'choice',
      prompt: '職務経歴書や面接について、正直な気持ちは？',
      options: [
        { label: '一人で準備するのは不安', sublabel: '添削や相談がほしい', effects: { support: 1.3 } },
        { label: '自分で進められる', sublabel: '客観的なデータがあれば十分', effects: { support: -0.8, expertise: 0.4 } },
        { label: 'まだ考えたことがない', sublabel: '', effects: { speed: -0.5 } },
        { label: '得意分野なので問題ない', sublabel: '', effects: { support: -1, income: 0.5 } },
      ],
    },
    {
      id: 'q8',
      type: 'slider',
      prompt: '専門性を一つに絞り込むことに、抵抗はありますか？',
      lowAnchor: '絞り込みたくない',
      highAnchor: '絞り込みたい',
      trait: 'expertise',
      direction: 1,
    },
    {
      id: 'q9',
      type: 'choice',
      prompt: '副業や複業について、興味があるのは？',
      options: [
        { label: '今のスキルを副業にも活かしたい', sublabel: '', effects: { expertise: 0.8 } },
        { label: '未経験の新しいスキルを学びたい', sublabel: '', effects: { expertise: -0.8, speed: 0.5 } },
        { label: '特に興味はない、本業に集中したい', sublabel: '', effects: { income: 0.5, speed: -0.5 } },
        { label: '将来は独立・起業も視野に入れたい', sublabel: '', effects: { speed: 0.8, support: -0.5 } },
      ],
    },
    {
      id: 'q10',
      type: 'slider',
      prompt: '複数のサービスやエージェントを比較しながら、慎重に進めたいですか？',
      lowAnchor: 'スピード優先で一つに絞りたい',
      highAnchor: 'じっくり比較したい',
      trait: 'speed',
      direction: -1,
    },
    {
      id: 'q11',
      type: 'choice',
      prompt: '転職・キャリアの相談で、一番欲しいものは？',
      options: [
        { label: '隣で一緒に考えてくれる人', sublabel: '', effects: { support: 1.3 } },
        { label: '客観的なデータと根拠', sublabel: '', effects: { support: -0.5, expertise: 0.5 } },
        { label: '背中を押してくれるきっかけ', sublabel: '', effects: { speed: 1 } },
        { label: '高い条件を引き出す交渉力', sublabel: '', effects: { income: 1.3 } },
      ],
    },
    {
      id: 'q12',
      type: 'slider',
      prompt: '最後に。「本当はもっと評価されたい」という気持ちは、どのくらいありますか？',
      lowAnchor: 'あまりない',
      highAnchor: 'かなりある',
      trait: 'income',
      direction: 1,
    },
  ],
  services: [
    {
      id: 'companion-agent',
      name: '伴走型キャリアエージェント',
      tagline: '書類添削から面接対策まで、二人三脚で進めたい人へ',
      emoji: '🤝',
      matchProfile: { support: { min: 0.5 } },
      href: 'https://www.r-agent.com/',
      isAffiliate: false,
      comingSoon: false,
    },
    {
      id: 'highclass-agent',
      name: 'ハイクラス転職エージェント',
      tagline: '高待遇・非公開求人を中心に、収入アップを狙いたい人へ',
      emoji: '💼',
      matchProfile: { income: { min: 0.5 }, support: { max: 0.3 } },
      href: 'https://doda.jp/',
      isAffiliate: false,
      comingSoon: false,
    },
    {
      id: 'specialist-school',
      name: '資格スクエア',
      tagline: '合格者のビッグデータで学ぶ、一つの分野を極めたい人へ',
      emoji: '🎯',
      matchProfile: { expertise: { min: 0.5 } },
      href: 'https://px.a8.net/svt/ejp?a8mat=4B5PG6+7O97SA+373C+67JUA',
      isAffiliate: true,
      comingSoon: false,
    },
    {
      id: 'fast-action-platform',
      name: 'スピード転職プラットフォーム',
      tagline: '今すぐ動いて、最短で次のステージに進みたい人へ',
      emoji: '⚡',
      matchProfile: { speed: { min: 0.5 } },
      href: 'https://www.mynavi-agent.jp/',
      isAffiliate: false,
      comingSoon: false,
    },
    {
      id: 'broad-explore-agent',
      name: '総合型転職エージェント',
      tagline: '視野を広げながら、色々な可能性を比較したい人へ',
      emoji: '🧭',
      matchProfile: { expertise: { max: -0.2 } },
      href: 'https://townwork.net/',
      isAffiliate: false,
      comingSoon: false,
    },
  ],
};
