import type { DiagnosisV2Config } from '@/types/diagnosisV2';

export const aiAptitudeV2: DiagnosisV2Config = {
  id: 'ai',
  title: 'AI活用適性診断',
  subtitle: '12の質問で、あなたに合うAIとの付き合い方が見えてきます',
  traits: [
    {
      key: 'automation',
      label: '自動化志向',
      lowLabel: '人の手を残したい',
      highLabel: '作業を自動化したい',
      color: '#38A1D6',
    },
    {
      key: 'creativity',
      label: '創造性活用',
      lowLabel: '実務効率化が目的',
      highLabel: '創造的な仕事に使いたい',
      color: '#D4AF37',
    },
    {
      key: 'learning',
      label: '学習意欲',
      lowLabel: 'シンプルなものだけでいい',
      highLabel: 'どんどん新しいツールを試したい',
      color: '#8FB8E0',
    },
    {
      key: 'monetize',
      label: '収益化志向',
      lowLabel: '今の仕事の効率化で十分',
      highLabel: 'AIスキルを稼ぐ力にしたい',
      color: '#C0D6F2',
    },
  ],
  questions: [
    {
      id: 'q1',
      type: 'choice',
      prompt: '今、AIツールをどのくらい使っていますか？',
      options: [
        { label: 'ほとんど使ったことがない', sublabel: '', effects: { learning: -0.8 } },
        { label: '少し触ったことがある程度', sublabel: '', effects: { learning: -0.3 } },
        { label: '日常的に使っている', sublabel: '', effects: { learning: 0.6 } },
        { label: '複数のツールを使いこなしている', sublabel: '', effects: { learning: 1.3, monetize: 0.5 } },
      ],
    },
    {
      id: 'q2',
      type: 'slider',
      prompt: '繰り返しの作業は、できるだけAIに任せたいですか？',
      lowAnchor: '自分の手でやりたい部分も残したい',
      highAnchor: 'できる限り自動化したい',
      trait: 'automation',
      direction: 1,
    },
    {
      id: 'q3',
      type: 'choice',
      prompt: 'AIを使う目的として、一番しっくりくるのは？',
      options: [
        { label: '今の業務をもっと早く正確にしたい', sublabel: '', effects: { automation: 1, creativity: -0.5 } },
        { label: '新しいアイデアや表現を広げたい', sublabel: '', effects: { creativity: 1.3 } },
        { label: '苦手な作業を肩代わりしてほしい', sublabel: '', effects: { automation: 0.8 } },
        { label: 'AI自体を仕事にしていきたい', sublabel: '', effects: { monetize: 1.3, learning: 0.6 } },
      ],
    },
    {
      id: 'q4',
      type: 'slider',
      prompt: '新しいAIツールが出たとき、すぐ試してみたいタイプですか？',
      lowAnchor: '必要になってから使う',
      highAnchor: 'とりあえず試してみたい',
      trait: 'learning',
      direction: 1,
    },
    {
      id: 'q5',
      type: 'choice',
      prompt: '文章・画像・動画など、AIでの創作活動についてどう感じますか？',
      options: [
        { label: 'あまり興味がない', sublabel: '', effects: { creativity: -1 } },
        { label: '実務の範囲で少し使う程度でいい', sublabel: '', effects: { creativity: -0.3 } },
        { label: '趣味や副業として楽しみたい', sublabel: '', effects: { creativity: 0.9, monetize: 0.4 } },
        { label: '本格的に創作の幅を広げたい', sublabel: '', effects: { creativity: 1.4 } },
      ],
    },
    {
      id: 'q6',
      type: 'slider',
      prompt: 'AIで効率化した時間を、何に使いたいですか？（高いほど新しい挑戦に使いたい）',
      lowAnchor: '今の仕事をより丁寧にやりたい',
      highAnchor: '新しいことに挑戦する時間にしたい',
      trait: 'monetize',
      direction: 1,
    },
    {
      id: 'q7',
      type: 'choice',
      prompt: 'AIスキルを身につけることについて、本音は？',
      options: [
        { label: '最低限使えれば十分', sublabel: '', effects: { learning: -0.6, monetize: -0.6 } },
        { label: '仕事で困らない程度には身につけたい', sublabel: '', effects: { learning: 0.4 } },
        { label: '人に教えられるくらい極めたい', sublabel: '', effects: { learning: 1.2, monetize: 0.6 } },
        { label: 'AI活用を新しい収入源にしたい', sublabel: '', effects: { monetize: 1.4 } },
      ],
    },
    {
      id: 'q8',
      type: 'slider',
      prompt: '人とのやり取りが必要な作業も、AIに任せたいと思いますか？',
      lowAnchor: '人との関わりは残したい',
      highAnchor: 'AIに任せられるなら任せたい',
      trait: 'automation',
      direction: 1,
    },
    {
      id: 'q9',
      type: 'choice',
      prompt: 'AI活用で一番ハードルに感じていることは？',
      options: [
        { label: '何から学べばいいか分からない', sublabel: '', effects: { learning: -0.4 } },
        { label: '使いこなせるか自信がない', sublabel: '', effects: { learning: -0.6, automation: -0.4 } },
        { label: '時間が取れない', sublabel: '', effects: { automation: 0.6 } },
        { label: '特にハードルは感じていない', sublabel: '', effects: { learning: 0.8, monetize: 0.5 } },
      ],
    },
    {
      id: 'q10',
      type: 'slider',
      prompt: 'AIで自動化できる作業を、業務の中でどのくらい見つけられていますか？',
      lowAnchor: 'あまり見つけられていない',
      highAnchor: 'かなり見つけられている',
      trait: 'automation',
      direction: 1,
    },
    {
      id: 'q11',
      type: 'choice',
      prompt: 'もしAI活用が得意になったら、何に活かしたいですか？',
      options: [
        { label: '今の仕事をもっと楽にしたい', sublabel: '', effects: { automation: 0.8, monetize: -0.5 } },
        { label: '副業や新しい収入源にしたい', sublabel: '', effects: { monetize: 1.2 } },
        { label: '創作やコンテンツ作りに活かしたい', sublabel: '', effects: { creativity: 1 } },
        { label: '人に教えたり広めたりしたい', sublabel: '', effects: { learning: 0.8, monetize: 0.6 } },
      ],
    },
    {
      id: 'q12',
      type: 'slider',
      prompt: '最後に。「AIをもっと自分の力にしたい」という気持ちは、どのくらいありますか？',
      lowAnchor: 'あまりない',
      highAnchor: 'かなりある',
      trait: 'learning',
      direction: 1,
    },
  ],
  services: [
    {
      id: 'automation-tool',
      name: '業務自動化ツール・サービス',
      tagline: '繰り返しの作業をAIに任せて、時間を生み出したい人へ',
      emoji: '⚙️',
      matchProfile: { automation: { min: 0.5 } },
      href: 'https://zapier.com/',
      isAffiliate: false,
      comingSoon: false,
    },
    {
      id: 'creative-ai-tool',
      name: 'AIクリエイティブツール',
      tagline: '文章・画像・動画など、創作の幅を広げたい人へ',
      emoji: '🎨',
      matchProfile: { creativity: { min: 0.5 } },
      href: 'https://www.canva.com/',
      isAffiliate: false,
      comingSoon: false,
    },
    {
      id: 'ai-learning-school',
      name: 'AI活用実践スクール',
      tagline: '新しいツールをどんどん学んで使いこなしたい人へ',
      emoji: '🧠',
      matchProfile: { learning: { min: 0.5 } },
      href: 'https://www.udemy.com/',
      isAffiliate: false,
      comingSoon: false,
    },
    {
      id: 'ai-monetize-program',
      name: 'AIスキル収益化プログラム',
      tagline: 'AI活用そのものを新しい収入源にしたい人へ',
      emoji: '💰',
      matchProfile: { monetize: { min: 0.5 } },
      href: 'https://coconala.com/',
      isAffiliate: false,
      comingSoon: false,
    },
    {
      id: 'simple-ai-starter',
      name: 'やさしいAI入門ガイド',
      tagline: 'まずは無理なく、基本から始めたい人へ',
      emoji: '🌱',
      matchProfile: { learning: { max: -0.2 } },
      href: 'https://claude.ai/',
      isAffiliate: false,
      comingSoon: false,
    },
  ],
};
