import type { DiagnosisV2Config } from '@/types/diagnosisV2';

export const careerStartV2: DiagnosisV2Config = {
  id: 'career',
  title: '就活キャリア診断',
  subtitle: '12の質問で、あなたに合う就活の進め方が見えてきます',
  traits: [
    {
      key: 'stability',
      label: '安定志向',
      lowLabel: '挑戦的な環境がいい',
      highLabel: '安定した環境がいい',
      color: '#38A1D6',
    },
    {
      key: 'expression',
      label: '自己表現力',
      lowLabel: '言語化に自信がない',
      highLabel: '自己PRに自信がある',
      color: '#D4AF37',
    },
    {
      key: 'clarity',
      label: '業界明確度',
      lowLabel: 'まだ模索中',
      highLabel: '志望業界が明確',
      color: '#8FB8E0',
    },
    {
      key: 'guidance',
      label: 'サポート希求度',
      lowLabel: '自分のペースで進めたい',
      highLabel: '手厚い対策がほしい',
      color: '#C0D6F2',
    },
  ],
  questions: [
    {
      id: 'q1',
      type: 'choice',
      prompt: '今の就活の状況に、一番近いものは？',
      options: [
        { label: 'まだ何も始めていない', sublabel: '', effects: { clarity: -0.8, guidance: 0.6 } },
        { label: '情報収集を始めたところ', sublabel: '', effects: { clarity: -0.3 } },
        { label: 'エントリーを始めている', sublabel: '', effects: { clarity: 0.5 } },
        { label: '面接段階まで進んでいる', sublabel: '', effects: { clarity: 0.9, expression: 0.4 } },
      ],
    },
    {
      id: 'q2',
      type: 'slider',
      prompt: '就活で重視したいのは、安定性と挑戦のどちらに近いですか？',
      lowAnchor: '挑戦できる環境がいい',
      highAnchor: '安定した環境がいい',
      trait: 'stability',
      direction: 1,
    },
    {
      id: 'q3',
      type: 'choice',
      prompt: '自己PRや面接への自信は、正直どのくらいありますか？',
      options: [
        { label: 'かなり不安が大きい', sublabel: '', effects: { expression: -1.3, guidance: 1 } },
        { label: '少し自信がない', sublabel: '', effects: { expression: -0.6, guidance: 0.5 } },
        { label: 'まあまあ自信がある', sublabel: '', effects: { expression: 0.6 } },
        { label: '自信がある', sublabel: '', effects: { expression: 1.3, guidance: -0.5 } },
      ],
    },
    {
      id: 'q4',
      type: 'slider',
      prompt: '志望する業界や職種は、どのくらい絞れていますか？',
      lowAnchor: 'まだ絞れていない',
      highAnchor: 'かなり絞れている',
      trait: 'clarity',
      direction: 1,
    },
    {
      id: 'q5',
      type: 'choice',
      prompt: '就活エージェントや支援サービスに期待するのは？',
      options: [
        { label: '一緒に考えてくれる伴走サポート', sublabel: '', effects: { guidance: 1.3 } },
        { label: '客観的な企業データや情報', sublabel: '', effects: { guidance: -0.3, clarity: 0.4 } },
        { label: '面接や書類の具体的な添削', sublabel: '', effects: { expression: -0.5, guidance: 0.8 } },
        { label: '特にサポートは不要、自分でやれる', sublabel: '', effects: { guidance: -1.2, expression: 0.5 } },
      ],
    },
    {
      id: 'q6',
      type: 'slider',
      prompt: '大手企業とベンチャー企業、本音はどちらに惹かれますか？',
      lowAnchor: 'ベンチャーで裁量を持ちたい',
      highAnchor: '大手で安定して働きたい',
      trait: 'stability',
      direction: 1,
    },
    {
      id: 'q7',
      type: 'choice',
      prompt: '自分の強みを聞かれたとき、どう感じますか？',
      options: [
        { label: 'うまく言葉にできない', sublabel: '', effects: { expression: -1.2, guidance: 0.8 } },
        { label: '考えればなんとか言える', sublabel: '', effects: { expression: -0.3 } },
        { label: 'いくつか具体的に言える', sublabel: '', effects: { expression: 0.7 } },
        { label: 'エピソードを交えて明確に言える', sublabel: '', effects: { expression: 1.4 } },
      ],
    },
    {
      id: 'q8',
      type: 'slider',
      prompt: '業界研究や企業研究は、どのくらい進んでいますか？',
      lowAnchor: 'まだほとんどできていない',
      highAnchor: 'かなり研究できている',
      trait: 'clarity',
      direction: 1,
    },
    {
      id: 'q9',
      type: 'choice',
      prompt: '就活で一番不安に感じていることは？',
      options: [
        { label: '何から始めればいいか分からない', sublabel: '', effects: { guidance: 1.2, clarity: -0.5 } },
        { label: '面接でうまく話せるか', sublabel: '', effects: { expression: -0.8 } },
        { label: '本当にやりたいことが分からない', sublabel: '', effects: { clarity: -1, guidance: 0.6 } },
        { label: '内定が取れるか競争が不安', sublabel: '', effects: { stability: 0.5, guidance: 0.4 } },
      ],
    },
    {
      id: 'q10',
      type: 'slider',
      prompt: '複数の選考対策を一人で進めるより、誰かと一緒に進めたいですか？',
      lowAnchor: '自分のペースで進めたい',
      highAnchor: '誰かと一緒に進めたい',
      trait: 'guidance',
      direction: 1,
    },
    {
      id: 'q11',
      type: 'choice',
      prompt: '働き方として、理想に近いのはどちらですか？',
      options: [
        { label: '腰を据えて長く働ける環境', sublabel: '', effects: { stability: 1.2 } },
        { label: '成長機会が多い環境', sublabel: '', effects: { stability: -0.8 } },
        { label: '専門性を磨ける環境', sublabel: '', effects: { clarity: 0.6 } },
        { label: 'まだ具体的にイメージできていない', sublabel: '', effects: { clarity: -0.6, guidance: 0.5 } },
      ],
    },
    {
      id: 'q12',
      type: 'slider',
      prompt: '最後に。「内定をしっかり勝ち取りたい」という気持ちは、どのくらい強いですか？',
      lowAnchor: 'プレッシャーは感じたくない',
      highAnchor: '強く勝ち取りたい',
      trait: 'expression',
      direction: 1,
    },
  ],
  services: [
    {
      id: 'companion-job-agent',
      name: '就職エージェントneo',
      tagline: '何から始めればいいか分からない人と、自己分析から一緒に進めるサポート',
      emoji: '🤝',
      matchProfile: { guidance: { min: 0.5 } },
      href: 'https://www.s-agent.jp/',
      isAffiliate: false,
      comingSoon: false,
    },
    {
      id: 'stable-company-navi',
      name: 'キャリアチケット就職エージェント',
      tagline: '社風や働きやすさを重視して、腰を据えて長く働ける環境を探したい人へ',
      emoji: '🏢',
      matchProfile: { stability: { min: 0.5 } },
      href: 'https://careerticket.jp/',
      isAffiliate: false,
      comingSoon: false,
    },
    {
      id: 'startup-job-platform',
      name: 'Wantedly',
      tagline: '裁量を持って挑戦できる、成長企業・ベンチャーで働きたい人へ',
      emoji: '🚀',
      matchProfile: { stability: { max: -0.3 } },
      href: 'https://www.wantedly.com/',
      isAffiliate: false,
      comingSoon: false,
    },
    {
      id: 'self-pr-coaching',
      name: '第二新卒エージェントneo',
      tagline: '自分の強みをうまく言葉にできない人と一緒に、自己PRから組み立てるサポート',
      emoji: '✍️',
      matchProfile: { expression: { max: -0.3 } },
      href: 'https://www.daini-agent.jp/',
      isAffiliate: false,
      comingSoon: false,
    },
    {
      id: 'industry-explore-tool',
      name: 'マイナビエージェント',
      tagline: 'まだ志望業界が定まっていない人へ、幅広い業界・職種の情報を',
      emoji: '🔍',
      matchProfile: { clarity: { max: -0.3 } },
      href: 'https://mynavi-agent.jp/',
      isAffiliate: false,
      comingSoon: false,
    },
  ],
};
