import type { DiagnosisV2Config } from '@/types/diagnosisV2';

export const careerChangeV2: DiagnosisV2Config = {
  id: 'career-change',
  title: '転職市場価値診断',
  subtitle: '12の質問で、あなたの今の市場価値と動くべきタイミングが見えてきます',
  traits: [
    {
      key: 'urgency',
      label: '緊急度',
      lowLabel: '様子を見ながら考えたい',
      highLabel: '今すぐ動きたい',
      color: '#38A1D6',
    },
    {
      key: 'selfAwareness',
      label: '市場価値自覚度',
      lowLabel: '客観視できていない',
      highLabel: '自分の価値を把握している',
      color: '#D4AF37',
    },
    {
      key: 'negotiation',
      label: '条件交渉志向',
      lowLabel: '提示条件で十分',
      highLabel: '積極的に交渉したい',
      color: '#8FB8E0',
    },
    {
      key: 'comparison',
      label: '比較検討志向',
      lowLabel: '一つに絞って深く考えたい',
      highLabel: '多くの選択肢を比較したい',
      color: '#C0D6F2',
    },
  ],
  questions: [
    {
      id: 'q1',
      type: 'choice',
      prompt: '今の自分の市場価値について、正直にどう感じていますか？',
      options: [
        { label: '全く把握できていない', sublabel: '', effects: { selfAwareness: -1.3 } },
        { label: 'なんとなくのイメージはある', sublabel: '', effects: { selfAwareness: -0.4 } },
        { label: 'ある程度具体的に把握している', sublabel: '', effects: { selfAwareness: 0.7 } },
        { label: '数字やデータで把握している', sublabel: '', effects: { selfAwareness: 1.4, negotiation: 0.5 } },
      ],
    },
    {
      id: 'q2',
      type: 'slider',
      prompt: '転職を考えるなら、今すぐ動きたい気持ちはどのくらいありますか？',
      lowAnchor: 'まだ様子を見たい',
      highAnchor: '今すぐ動きたい',
      trait: 'urgency',
      direction: 1,
    },
    {
      id: 'q3',
      type: 'choice',
      prompt: '転職を考え始めたきっかけに、一番近いものは？',
      options: [
        { label: '今の給与に納得していない', sublabel: '', effects: { negotiation: 1, urgency: 0.5 } },
        { label: '将来への漠然とした不安', sublabel: '', effects: { urgency: -0.4, selfAwareness: -0.4 } },
        { label: '今より良い環境を試したい', sublabel: '', effects: { comparison: 0.8 } },
        { label: '特に強いきっかけはまだない', sublabel: '', effects: { urgency: -0.9 } },
      ],
    },
    {
      id: 'q4',
      type: 'slider',
      prompt: '年収や条件の交渉について、積極的にやりたいですか？',
      lowAnchor: '提示された条件で十分',
      highAnchor: '積極的に交渉したい',
      trait: 'negotiation',
      direction: 1,
    },
    {
      id: 'q5',
      type: 'choice',
      prompt: '転職活動の進め方として、しっくりくるのは？',
      options: [
        { label: '一社ずつじっくり検討したい', sublabel: '', effects: { comparison: -1 } },
        { label: '複数社を並行して比較したい', sublabel: '', effects: { comparison: 1.2 } },
        { label: 'まずは情報収集だけしたい', sublabel: '', effects: { urgency: -0.6, comparison: 0.4 } },
        { label: '良い話があればすぐ動きたい', sublabel: '', effects: { urgency: 1, comparison: -0.4 } },
      ],
    },
    {
      id: 'q6',
      type: 'slider',
      prompt: '今の年収は、自分の実力に見合っていると感じますか？',
      lowAnchor: '見合っていないと感じる',
      highAnchor: '見合っていると感じる',
      trait: 'negotiation',
      direction: -1,
    },
    {
      id: 'q7',
      type: 'choice',
      prompt: '自分の経歴やスキルを、客観的なデータと照らし合わせたことはありますか？',
      options: [
        { label: 'まったくない', sublabel: '', effects: { selfAwareness: -1 } },
        { label: 'なんとなく調べたことがある', sublabel: '', effects: { selfAwareness: -0.3 } },
        { label: '一度しっかり診断したことがある', sublabel: '', effects: { selfAwareness: 0.8 } },
        { label: '定期的に市場価値をチェックしている', sublabel: '', effects: { selfAwareness: 1.3, urgency: 0.4 } },
      ],
    },
    {
      id: 'q8',
      type: 'slider',
      prompt: '転職先候補は、できるだけ多く比較したいですか？',
      lowAnchor: '一つに絞って深く考えたい',
      highAnchor: 'たくさん比較したい',
      trait: 'comparison',
      direction: 1,
    },
    {
      id: 'q9',
      type: 'choice',
      prompt: '今、転職に踏み切れない一番の理由は？',
      options: [
        { label: '自分の市場価値に自信が持てない', sublabel: '', effects: { selfAwareness: -1, urgency: -0.5 } },
        { label: '今より悪い条件になるのが怖い', sublabel: '', effects: { negotiation: -0.6 } },
        { label: '何から始めればいいか分からない', sublabel: '', effects: { urgency: -0.4, comparison: 0.4 } },
        { label: '特に踏み切れない理由はない', sublabel: '', effects: { urgency: 1.2 } },
      ],
    },
    {
      id: 'q10',
      type: 'slider',
      prompt: '今の市場での「旬」を逃したくないという焦りはありますか？',
      lowAnchor: 'あまり焦りはない',
      highAnchor: 'かなり焦りがある',
      trait: 'urgency',
      direction: 1,
    },
    {
      id: 'q11',
      type: 'choice',
      prompt: '転職活動で一番欲しいサポートは？',
      options: [
        { label: '客観的な市場価値の診断', sublabel: '', effects: { selfAwareness: 0.8 } },
        { label: '条件交渉の代行・アドバイス', sublabel: '', effects: { negotiation: 1.1 } },
        { label: '多くの求人を一気に見比べる手段', sublabel: '', effects: { comparison: 1 } },
        { label: '今動くべきかどうかの判断材料', sublabel: '', effects: { urgency: 0.6, selfAwareness: 0.4 } },
      ],
    },
    {
      id: 'q12',
      type: 'slider',
      prompt: '最後に。「今の自分の市場価値を正確に知りたい」という気持ちは、どのくらいありますか？',
      lowAnchor: 'あまりない',
      highAnchor: 'かなりある',
      trait: 'selfAwareness',
      direction: 1,
    },
  ],
  services: [
    {
      id: 'market-value-check',
      name: '市場価値診断・年収査定サービス',
      tagline: '自分の市場価値をまず客観的に把握したい人へ',
      emoji: '📊',
      matchProfile: { selfAwareness: { max: -0.2 } },
      href: 'https://doda.jp/',
      isAffiliate: false,
      comingSoon: false,
    },
    {
      id: 'negotiation-agent',
      name: '年収交渉に強いエージェント',
      tagline: '今の条件に納得しておらず、しっかり交渉したい人へ',
      emoji: '💴',
      matchProfile: { negotiation: { min: 0.5 } },
      href: 'https://www.r-agent.com/',
      isAffiliate: false,
      comingSoon: false,
    },
    {
      id: 'multi-compare-platform',
      name: '求人比較プラットフォーム',
      tagline: '多くの選択肢を一気に比較検討したい人へ',
      emoji: '⚖️',
      matchProfile: { comparison: { min: 0.5 } },
      href: 'https://townwork.net/',
      isAffiliate: false,
      comingSoon: false,
    },
    {
      id: 'fast-move-agent',
      name: 'スピード転職サポート',
      tagline: '今すぐ動きたい、旬を逃したくない人へ',
      emoji: '⏱️',
      matchProfile: { urgency: { min: 0.6 } },
      href: 'https://www.mynavi-agent.jp/',
      isAffiliate: false,
      comingSoon: false,
    },
    {
      id: 'wait-and-prepare-guide',
      name: 'じっくり準備型キャリア相談',
      tagline: 'まだ様子を見ながら、焦らず考えたい人へ',
      emoji: '🌙',
      matchProfile: { urgency: { max: -0.3 } },
      href: 'https://www.bizreach.jp/',
      isAffiliate: false,
      comingSoon: false,
    },
  ],
};
