import type { DiagnosisV2Config } from '@/types/diagnosisV2';

export const sideHustleV2: DiagnosisV2Config = {
  id: 'side-hustle',
  title: '副業適性診断',
  subtitle: '12の質問で、あなたに合う副業のかたちが見えてきます',
  traits: [
    {
      key: 'time',
      label: '時間投資度',
      lowLabel: 'スキマ時間で完結したい',
      highLabel: 'がっつり時間を使いたい',
      color: '#38A1D6',
    },
    {
      key: 'skill',
      label: 'スキル活用度',
      lowLabel: '新しいことを学びたい',
      highLabel: '今のスキルを活かしたい',
      color: '#D4AF37',
    },
    {
      key: 'risk',
      label: 'リスク許容度',
      lowLabel: '低リスクで着実に',
      highLabel: 'リスクを取って大きく',
      color: '#8FB8E0',
    },
    {
      key: 'visibility',
      label: '発信・対外性',
      lowLabel: '黙々と作業したい',
      highLabel: '人前に出て発信したい',
      color: '#C0D6F2',
    },
  ],
  questions: [
    {
      id: 'q1',
      type: 'choice',
      prompt: '副業に対する今の気持ちに、一番近いものは？',
      options: [
        { label: 'まだ漠然と気になっている程度', sublabel: '', effects: { risk: -0.8, time: -0.5 } },
        { label: '具体的に検討し始めている', sublabel: '', effects: { time: 0.5 } },
        { label: 'すでに少し動いている', sublabel: '', effects: { time: 0.8, risk: 0.5 } },
        { label: '本業以上に育てたいと思っている', sublabel: '', effects: { time: 1.3, risk: 1 } },
      ],
    },
    {
      id: 'q2',
      type: 'slider',
      prompt: '副業に使える時間は、本音ではどのくらい確保したいですか？',
      lowAnchor: '週数時間のスキマ時間で',
      highAnchor: 'まとまった時間を使いたい',
      trait: 'time',
      direction: 1,
    },
    {
      id: 'q3',
      type: 'choice',
      prompt: '今のスキルや経験について、副業でどう活かしたいですか？',
      options: [
        { label: '今の仕事のスキルをそのまま活かしたい', sublabel: '', effects: { skill: 1.3 } },
        { label: '今のスキルを少しアレンジして使いたい', sublabel: '', effects: { skill: 0.6 } },
        { label: '全く新しいことに挑戦したい', sublabel: '', effects: { skill: -1.3 } },
        { label: 'まだ分からない、探りながら決めたい', sublabel: '', effects: { skill: -0.3, time: -0.4 } },
      ],
    },
    {
      id: 'q4',
      type: 'slider',
      prompt: '失敗やリスクへの抵抗感は、どのくらいありますか？',
      lowAnchor: '低リスクで着実に進めたい',
      highAnchor: 'リスクを取ってでも大きく狙いたい',
      trait: 'risk',
      direction: 1,
    },
    {
      id: 'q5',
      type: 'choice',
      prompt: '人前に出ることや発信することについて、本音は？',
      options: [
        { label: '顔や名前を出すのは抵抗がある', sublabel: '', effects: { visibility: -1.3 } },
        { label: '匿名なら発信してもいい', sublabel: '', effects: { visibility: -0.4 } },
        { label: '機会があれば前に出てみたい', sublabel: '', effects: { visibility: 0.6 } },
        { label: 'むしろ発信して影響力を持ちたい', sublabel: '', effects: { visibility: 1.4, risk: 0.5 } },
      ],
    },
    {
      id: 'q6',
      type: 'slider',
      prompt: 'すぐに成果が出るものと、長く続けて育てるもの、本音はどちらに惹かれますか？',
      lowAnchor: 'すぐに成果が欲しい',
      highAnchor: 'じっくり育てたい',
      trait: 'time',
      direction: -1,
    },
    {
      id: 'q7',
      type: 'choice',
      prompt: '副業の初期投資（スクール・機材など）について、どう考えていますか？',
      options: [
        { label: 'お金はかけずに始めたい', sublabel: '', effects: { risk: -1 } },
        { label: '必要なら少しは投資してもいい', sublabel: '', effects: { risk: 0.3 } },
        { label: '本気でやるなら投資は惜しまない', sublabel: '', effects: { risk: 1.2, time: 0.5 } },
        { label: 'スクールなど学びへの投資に興味がある', sublabel: '', effects: { skill: -0.6, risk: 0.4 } },
      ],
    },
    {
      id: 'q8',
      type: 'slider',
      prompt: 'チームより、一人で黙々と進める方が性に合っていますか？',
      lowAnchor: '人と関わりながら進めたい',
      highAnchor: '一人で黙々と進めたい',
      trait: 'visibility',
      direction: -1,
    },
    {
      id: 'q9',
      type: 'choice',
      prompt: '将来的に、副業をどうしていきたいですか？',
      options: [
        { label: '本業の収入を少し補う程度でいい', sublabel: '', effects: { risk: -0.8, time: -0.5 } },
        { label: '本業と同じくらいの柱に育てたい', sublabel: '', effects: { time: 1, risk: 0.6 } },
        { label: 'ゆくゆくは独立・起業したい', sublabel: '', effects: { risk: 1.3, visibility: 0.6 } },
        { label: '複数の収入源を分散して持ちたい', sublabel: '', effects: { time: 0.4, skill: -0.4 } },
      ],
    },
    {
      id: 'q10',
      type: 'slider',
      prompt: 'AIツールなど新しい技術を積極的に使ってみたいですか？',
      lowAnchor: '使い慣れたやり方でいい',
      highAnchor: '新しい技術を積極的に使いたい',
      trait: 'skill',
      direction: -1,
    },
    {
      id: 'q11',
      type: 'choice',
      prompt: '副業を始めるとき、一番欲しいサポートは？',
      options: [
        { label: '何から始めればいいかの道筋', sublabel: '', effects: { time: -0.4, risk: -0.4 } },
        { label: '稼ぐためのスキルそのもの', sublabel: '', effects: { skill: -0.8 } },
        { label: '発信や集客のノウハウ', sublabel: '', effects: { visibility: 1 } },
        { label: '特にサポートは不要、自分でやれる', sublabel: '', effects: { risk: 0.6, skill: 0.6 } },
      ],
    },
    {
      id: 'q12',
      type: 'slider',
      prompt: '最後に。「本当は今の働き方以外の収入源が欲しい」という気持ちは、どのくらいありますか？',
      lowAnchor: 'あまりない',
      highAnchor: 'かなりある',
      trait: 'time',
      direction: 1,
    },
  ],
  services: [
    {
      id: 'home-based-work',
      name: '在宅ワーク・クラウドソーシング',
      tagline: 'スキマ時間で、低リスクに着実に始めたい人へ',
      emoji: '🏠',
      matchProfile: { time: { max: -0.2 }, risk: { max: 0 } },
      href: 'https://crowdworks.jp/',
      isAffiliate: false,
      comingSoon: false,
    },
    {
      id: 'skill-marketplace',
      name: 'スキル販売プラットフォーム',
      tagline: '今のスキルや経験をそのまま商品化したい人へ',
      emoji: '💡',
      matchProfile: { skill: { min: 0.4 } },
      href: 'https://coconala.com/',
      isAffiliate: false,
      comingSoon: false,
    },
    {
      id: 'freelance-invoice',
      name: 'ペイトナー',
      tagline: 'フリーランスの請求書を先払い。資金繰りを安定させたい人へ',
      emoji: '💸',
      matchProfile: { risk: { min: 0.4 }, skill: { min: 0.2 } },
      href: 'https://px.a8.net/svt/ejp?a8mat=4B5Q84+B9GA22+4PF6+609HU',
      isAffiliate: true,
      comingSoon: false,
    },
    {
      id: 'content-creator-platform',
      name: '発信・コンテンツ収益化プラットフォーム',
      tagline: '自分を発信して、影響力ごと収益にしたい人へ',
      emoji: '🎤',
      matchProfile: { visibility: { min: 0.5 } },
      href: 'https://note.com/',
      isAffiliate: false,
      comingSoon: false,
    },
    {
      id: 'independence-support',
      name: 'バーチャルオフィス NAWABARI',
      tagline: 'リスクを取ってでも、本気で独立・起業を目指したい人へ',
      emoji: '🚀',
      matchProfile: { risk: { min: 0.6 }, time: { min: 0.3 } },
      href: 'https://px.a8.net/svt/ejp?a8mat=4B5Q84+B8UUGA+4YOI+5YJRM',
      isAffiliate: true,
      comingSoon: false,
    },
  ],
};
